spring.application.name=server-moniter
server.servlet.context-path=/api

# PostgresSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/server_monitor
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# JWT
application.security.jwt.secret-key=kH9v2Lz/jN4mQ9pRx5T7wA8zC1bV2eR3F5gH6jK9mN4=

# Line
line.channel-access-token=JGLakvXxSNR5oBQQsurOP4ho8/S2CXO5IJ1dpm5BxXiNoPm/6jO5F8ViwFwXc7vNZA9rmXtQggqGlGB0eVICq2UURotmYVhLPS9PpjfsvdVzWZr+pw9XyL9liqvb+uiOG9V9EOMaS4baBil0IuqrMQdB04t89/1O/w1cDnyilFU=
